import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Music Next Js",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className = "dark">
        <div className="relative w-full flex items-center justify-center">
          <Navbar className="top-2"/>
        </div>
        {children}
        <div>
          <Footer/>
        </div>
      </body>
    </html>
  )
}
